### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dzyu1108** [kartik-joshi/Adversarial-Attack-on-Recurrent-Neural-Network#1]
Did your code test_attack.py use a image dataset to complete your L2 attack?
I mean that you attempted to attack LSTM model by L2 attack as you said in the readme.md, but your code showed that you used the CIFAR and MINIST dataset to complete the attack? Why?
May I have a wrong sense of the code? Thank you

**Comment by kartik-joshi** [comment]
I am performing L2 test on my RNN model only(Line 76 - LSTM model). I kept the original code in comments so that anyone wants to perfrom the same on CIFAR or MNIST models they can just coment out lines and plug in their model.

```
#data, model = RNN(), RNNModel("models\imdb_model.h5", sess)  #MNIST(), MNISTModel("models/mnist", sess)
data, model = RNN_Keras(), RNNModel_Keras("models\imdb_model.h5")
```
